#yml文件
server:
 port: 8080
 servlet:
  context-path: /hello
#properties文件
#server.port=8080
#在网址127.0.0.1:8080后加上/crud
#server.servlet.context-path=/crud
#-------------------------------------

#MyBatis配置
spring:
 datasource:
#  url: jdbc:mysql://192.168.116.129:3306/test
  url: jdbc:mysql://192.168.110.165:3306/test
  username: root
  password: 1234
  driver-class-name: com.mysql.jdbc.Driver
  
mybatis:
 type-aliases-package: com.example.demo.dao
 config-locations: mybatis/mybatis-config.xml
 mapper-locations: mybatis/mapper/*.xml

#spring.datasource.url 数据库连接字符串
#spring.datasource.username 数据库用户名
#spring.datasource.password 数据库密码
#spring.datasource.driver-class-name 驱动类型（注意MySQL 8.0的值是com.mysql.cj.jdbc.Driver和之前不同）
#mybatis.type-aliases-package 实体类包路径
#mybatis.config-locations 配置MyBatis基础属性
#mybatis.mapper-locations 配置Mapper XML文件
#----------------------------------------------------------

#mybatis-plus,在控制台打印sql语句以及结果
mybatis-plus:
 configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#----------------------------------------------------------
#redis
#   redis:
#    open: false  # 是否开启redis缓存  true开启   false关闭
#    database: 0
#    host: localhost
#    port: 6379
#    password:    # 密码（默认为空）
#    timeout: 6000ms  # 连接超时时长（毫秒）
#    jedis:
#     pool:
#      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#      max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-idle: 10      # 连接池中的最大空闲连接
#      min-idle: 5       # 连接池中的最小空闲连接

#swagger:
# enable: true